// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/upload": {
    params: {};
  };
  "/watch/:id": {
    params: {
      "id": string;
    };
  };
  "/shorts": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/upload" | "/watch/:id" | "/shorts";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/upload.tsx": {
    id: "routes/upload";
    page: "/upload";
  };
  "routes/watch.$id.tsx": {
    id: "routes/watch.$id";
    page: "/watch/:id";
  };
  "routes/shorts.tsx": {
    id: "routes/shorts";
    page: "/shorts";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/upload": typeof import("./app/routes/upload.tsx");
  "routes/watch.$id": typeof import("./app/routes/watch.$id.tsx");
  "routes/shorts": typeof import("./app/routes/shorts.tsx");
};